// <auto-generated />
namespace NewWq.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newwq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newwq));
        
        string IMigrationMetadata.Id
        {
            get { return "202002110617343_newwq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
